apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170419533
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170419533
    app.kubernetes.io/part-of: test-app-170419533
  name: java-quarkus-170419533
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170419533
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170419533
    spec:
      containers:
      - image: quay.io/hacdev/p5g1qgvi-tenant/test-app-170419533/java-quarkus-170419533@sha256:942721b4ca8ba69cb6b01953bf602463f5e786295eb71b51bbc768b59a5babae
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
