apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170419533
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/p5g1qgvi-tenant/test-app-170419533/java-quarkus-170419533@sha256:942721b4ca8ba69cb6b01953bf602463f5e786295eb71b51bbc768b59a5babae
        name: my-java-quarkus
        resources: {}
status: {}
